source/_patterns/01-molecules/51-borrower-dashboard/01-whats-next-content/14-refer-another-borrower.mustache
for review @BoulderBrains @emuvente
=> ZIP-2794 borrower invite link copy to clipboard

source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments.json, source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments.mustache
=> AUTO-14 base template for auto-repayments page

source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments.mustache
for review and merge to master - just adding the #paypal-button element needed to render the paypal button for the borrower dashboard auto-repayments view
=> AUTO-67 need #paypal-button element for rendering paypal button

source/_patterns/02-organisms/55-auto-deposit/01-auto-deposit-inputs.mustache, source/_patterns/03-templates/24-auto-deposit.mustache, source/css/scss/app/pages/auto-deposit.scss, source/css/scss/vendor_override/foundation/_forms.scss, source/js/inc/app.js
replaces previous PR but with fewer export files
=> ADEP-8 - cleaned commit

source/_patterns/02-organisms/50-trustee-dashboard/52-main-pending-endorsements-bar.mustache, source/css/scss/app/pages/trustee.scss
for review @foochris , @emuvente , @BoulderBrains
=> ZIP-2687 view more or less pending

source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments.mustache
for review - @leoperry 
fyi - @coderintherye , @ninapatel 
there's still some issues in that the decision lightbox seems to leak memory, and the getStatus method does not contain upcoming repayment information but we are getting much closer!
=> AUTO-31 unpause autorepayment - unstyled

source/_patterns/00-atoms/12-panels/00-panel.mustache, source/_patterns/00-atoms/12-panels/01-panel-callout.mustache, source/_patterns/02-organisms/50-borrower-dashboard/03-upcoming-repayments.mustache, source/_patterns/02-organisms/50-borrower-dashboard/03-upcoming-repayments~auto.json, source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments.mustache, source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments~active.json, source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments~paused.json, source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments~predisbursal.json, source/_patterns/03-templates/50-borrower-dashboard/51-borrower-dashboard.mustache, source/_patterns/03-templates/50-borrower-dashboard/51-borrower-dashboard~payingback-auto.json, source/_patterns/03-templates/50-borrower-dashboard/51-borrower-dashboard~payingback-delinquent.json, source/css/scss/_palette.scss, source/css/scss/app.scss, source/css/scss/vendor_override/foundation/_panels.scss
for review, plz - @jedlin-kiva , @emuvente , @BoulderBrains 
i've added a '.panel' and a '.panel.callout' atom.
i've also used a couple style tags here and there.
let me know if a better pattern jumps out at you.
=> Auto 27 dynamic content active

source/_patterns/02-organisms/50-borrower-dashboard/05-auto-repayments.mustache
@BoulderBrains  for your review.
=> sentence change autorepay

export/patterns/02-organisms/45-borrower-landing/04-tagline.mustache, export/patterns/02-organisms/45-borrower-landing/05-value-props.mustache, source/_patterns/02-organisms/45-borrower-landing/01-how-it-works-borrower.mustache, source/_patterns/02-organisms/45-borrower-landing/04-tagline.mustache, source/_patterns/02-organisms/45-borrower-landing/05-value-props.mustache
@BoulderBrains any chance you could review? these are very minor changes of the numbers on the landing page
=> Update number borrower landing

export/patterns/02-organisms/50-trustee-dashboard/52-main-pending-endorsements-bar.mustache, source/_patterns/02-organisms/50-trustee-dashboard/52-main-pending-endorsements-bar.mustache
Update to the text that shows for Trustees on their dashboard. @ninapatel for your review.
=> Zip 2879 trustee

source/_patterns/02-organisms/22-settings/01-auto-deposit-settings.json, source/_patterns/02-organisms/22-settings/01-auto-deposit-settings.mustache, source/_patterns/02-organisms/22-settings/01-auto-deposit-settings~AD-off-MG-off.json, source/_patterns/02-organisms/22-settings/01-auto-deposit-settings~MG-on-AD-on.json, source/_patterns/02-organisms/22-settings/02-monthly-good-subscription-settings.mustache
I flipped this back to underscores for consistency after I found the real issue on the kiva/main side. Please wait to merge until you've seen both PRs.
=> SUB-65 flipping these back for consistency.

Gruntfile.js
an example of the resulting commit: c5912c72d238961a3f49eb68a11c969b3377135b
=> update the shrinkwrap on release

source/_patterns/02-organisms/60-monthly-good/01-monthly-good-inputs.mustache, source/_patterns/03-templates/55-monthly-good/01-landing.mustache
A couple small naming updates got this validation working.
=> Sub 82 wip

source/css/scss/vendor_override/foundation/_reveal.scss
Picking off low hanging fruit :kiwi_fruit:
=> LW-101 creating hover state for .close-reveal-modal x icon.

source/css/scss/app/pages/about.scss, source/css/scss/app/pages/fellows.scss
Updated image in CMS entry first adding update svg image here: https://pages.kiva.org/xb/about
=> Update image url for about and fellows globe svg background image.

source/_patterns/02-organisms/07-categorycards/06-category-monthly-good-promo.mustache
=> LW-1513 slide-overlay-short -> slide-overlay

source/css/scss/app/pages/finding.scss
Haha it's funny we looked at that and saw two different issues (me the border color and you the svg lines on hover). I'm glad they are both fixed now, the button looks way better with the white svg lines. Thanks for the review Jim.
=> LW-1568 changing svg color on hover of filters button

source/css/scss/app/paging.scss
Fixes pagination on /lend page, in the way that I'm forcing buttons not to look like buttons as requested.
=> LW-1573 fixing first/last pagination on /lend

source/_patterns/02-organisms/04-loancards/10-loancard-2.mustache, source/css/scss/app/loancards-2.scss
moving the fav star on new loan cards, changing styles slightly.
=> LW-1529 moving and styling favorite star on new loan card

source/_patterns/03-templates/22-add-credit.mustache
auto-deposit always on, eck always active
=> Feature braincc 167 deposit view pp

source/css/scss/app/pages/borrower-landing.scss
Just got this random request, wasn't hard to make, so I just did it.
=> small spacing adjustment

source/_patterns/02-organisms/00-global/04-gdpr-notice.json, source/_patterns/02-organisms/00-global/04-gdpr-notice.mustache, source/css/scss/_palette.scss, source/css/scss/app.scss, source/css/scss/app/gdpr-notice.scss
@ksekhri Slightly different approach with the markup and scss to remove duplicate html markup, using breakpoints to alter the styles and show header content only on mobile/medium.
=> Ml 68 gdpr notice

source/_patterns/01-molecules/08-meters/appeal-meter.json, source/_patterns/01-molecules/08-meters/appeal-meter.mustache, source/_patterns/02-organisms/00-global/02-sitewide-appeal.json, source/_patterns/02-organisms/00-global/02-sitewide-appeal.mustache, source/css/scss/app/sitewide-appeal.scss, source/css/scss/vendor_override/foundation/_buttons.scss
New midyear appeal thermometer.
=> Mid year appeal

source/_patterns/02-organisms/00-global/02-sitewide-appeal.mustache, source/css/scss/app/sitewide-appeal.scss
=> cash-772 tweaks to midyear appeal after seeing it with other elements

source/_patterns/01-molecules/08-meters/appeal-meter.mustache, source/_patterns/02-organisms/00-global/02-sitewide-appeal.mustache, source/css/scss/app/sitewide-appeal.scss
Pull request for additional styleguide changes. Not yet ready for merge, would like to leave this open until cash-771 is reviewed and merged into /kiva/ui just incase additional changes come up in that stack.
=> Appeal changes

source/_patterns/02-organisms/00-global/02-sitewide-appeal.mustache
We had a last minute update to the midyear appeal happen today. We're extending the promotion by a day with different language. Here's the update on the /kiva/styleguide side.
=> cash-942 updating bonus text for mid-year appeal banner

source/_patterns/02-organisms/00-global/04-gdpr-notice.mustache, source/css/scss/app/gdpr-notice.scss
/kiva/styleguide side changes to replace x image with a "sounds good" button.
=> cash-1471 styleguide side adjustments, less scss is better

source/css/scss/app/gdpr-notice.scss
Small spacing fix for xlg screens
=> cash-1471 Little spacing cleanup for xlg screens

source/css/scss/app/global-promo.scss
=> Fixed icon flex shrink on mobile for global promo banner icon

source/_patterns/02-organisms/00-global/01-footer-spanish.json, source/_patterns/02-organisms/00-global/01-footer-spanish.mustache, source/_patterns/02-organisms/00-global/01-footer.json, source/_patterns/02-organisms/00-global/01-footer.mustache
Last group of changes related to footer link changes
=> webbug-2811 styleguide changes to footers for trustees -> hubs update

source/_patterns/02-organisms/40-portfolio/01-portfolio-main-top-bar.mustache
Very minor change I noticed, this probably doesn't need a release and can get rolled into the next release
=> Minor style change to portfolio

source/_patterns/02-organisms/40-portfolio/01-portfolio-main-top-bar.mustache
Corresponding PR in kiva/kiva:
https://github.com/kiva/kiva/pull/8847
=> Modified portfolio to include last manual loan time AUTO-69

source/_patterns/02-organisms/08-header/03-lend-menu.mustache
Here's the styleguide/XbLegacyNav changes related to grow-362, brings this inline with the changes I made the the nav on the /ui side in this branch: 
https://github.com/kiva/ui/pull/2555
=> grow-362 xbLegacyNav adding region tracking changes.

source/_patterns/03-templates/04-header.mustache
Activated by: https://github.com/kiva/kiva/pull/9624
=> Add new template option for MVP promo banner and link

source/_patterns/01-molecules/03-media/02-lender-avatar.mustache, source/_patterns/01-molecules/15-loan-sections/00-more-loan-info.mustache, source/_patterns/01-molecules/15-loan-sections/01-why-special.mustache, source/_patterns/01-molecules/15-loan-sections/06-loan-details.mustache, source/_patterns/01-molecules/15-loan-sections/07-lenders-teams.json, source/_patterns/01-molecules/15-loan-sections/07-lenders-teams.mustache, source/_patterns/01-molecules/15-loan-sections/18-loan-story.mustache, source/_patterns/01-molecules/15-loan-sections/19-about-zip-business.mustache, source/_patterns/01-molecules/15-loan-sections/20-trustee-details.mustache, source/_patterns/01-molecules/15-loan-sections/22-field-partner-details.mustache, source/_patterns/01-molecules/15-loan-sections/23-tags.mustache, source/_patterns/01-molecules/15-loan-sections/31-comments-and-updates.mustache, source/_patterns/04-pages/05-borrower-profile.mustache
Ticket: GROW-522
See related "Kiva Main" PR: https://github.com/kiva/kiva/pull/9819
=> GROW-522 Add more tracking in borrower profile

source/_patterns/02-organisms/04-loancards/10-loancard-2.mustache, source/css/scss/app/loancards-2.scss, source/images/icons.min/bookmark.svg
I had to reorganize the template in order to make the bookmarking more reactive. 
associated kiva/main changes:
Coming soon.
=> fix: core-217 updating templates and svg

source/_patterns/02-organisms/40-portfolio/12-portfolio-cta.json, source/_patterns/02-organisms/40-portfolio/12-portfolio-cta.mustache
=> feat: added additional CTA's for portfolio cta test

source/_patterns/03-templates/04-header.mustache, source/css/scss/app/header/top-nav.scss
Updated login button.
[MARS-298](https://kiva.atlassian.net/browse/MARS-298)
[Design](https://www.figma.com/file/tiaWcJ8gDQKhpzXXwkhe97/New-user-Journey?node-id=210%3A477)
=> MARS-298: Updated login button

source/_patterns/03-templates/50-borrower-dashboard/51-borrower-dashboard.mustache, source/_patterns/03-templates/50-borrower-dashboard/51-borrower-dashboard~payingback.json, source/css/scss/app/pages/borrower-dashboard.scss
Adds custom repayment amount input on borrower dashboard
ACK-410
=> feat: custom repayment amount input

core/source/_patterns/00-atoms/05-forms/00-text-fields.mustache, core/source/_patterns/01-molecules/00-text/01-address.mustache, core/source/_patterns/01-molecules/04-forms/01-comment-form.mustache, core/source/_patterns/01-molecules/04-forms/02-newsletter.mustache, export/patterns/01-molecules/40-portfolio/02-single-team-display.mustache, export/patterns/01-molecules/40-portfolio/04-loan-update.mustache, export/patterns/01-molecules/40-portfolio/07-my-loans-table-row.mustache, export/patterns/01-molecules/60-withdrawals/02-paypal-profile-iconography.mustache, export/patterns/02-organisms/21-messages/01-lender-message.mustache, export/patterns/02-organisms/22-settings/05-email-type-unsubscribe.mustache, export/patterns/02-organisms/40-portfolio/01-portfolio-main-top-bar.mustache, export/patterns/02-organisms/40-portfolio/04-portfolio-main-loans-bar.mustache, export/patterns/02-organisms/40-portfolio/09-my-loans-table.mustache, export/patterns/03-templates/04-header-spanish.mustache, export/patterns/03-templates/04-header.mustache, export/patterns/03-templates/21-withdraw-credit.mustache, export/patterns/03-templates/22-withdraw-credit-confirm.mustache, source/_patterns/01-molecules/40-portfolio/02-single-team-display.mustache, source/_patterns/01-molecules/40-portfolio/04-loan-update.mustache, source/_patterns/01-molecules/40-portfolio/07-my-loans-table-row.mustache, source/_patterns/01-molecules/60-withdrawals/02-paypal-profile-iconography.mustache, source/_patterns/02-organisms/21-messages/01-lender-message.mustache, source/_patterns/02-organisms/22-settings/05-email-type-unsubscribe.mustache, source/_patterns/02-organisms/40-portfolio/01-portfolio-main-top-bar.mustache, source/_patterns/02-organisms/40-portfolio/04-portfolio-main-loans-bar.mustache, source/_patterns/02-organisms/40-portfolio/09-my-loans-table.mustache, source/_patterns/03-templates/04-header-spanish.mustache, source/_patterns/03-templates/04-header.mustache, source/_patterns/03-templates/21-withdraw-credit.mustache, source/_patterns/03-templates/22-withdraw-credit-confirm.mustache
=> feat: add mask PII for hotjar

source/_patterns/02-organisms/08-header/01-search-button.mustache, source/_patterns/02-organisms/08-header/02-search-box.mustache, source/_patterns/03-templates/04-header.mustache, source/css/scss/app/header/search-box.scss, source/css/scss/app/header/top-nav.scss, source/js/inc/app/header.js
Search bar was broken on tablet, same error on cps and ui
=> Fix broken search bar
